### ISSUE TITLE
Provide an API for stable rust

### ISSUE THREAD

**Issue by sgrif** [ChrisBuchholz/accord#11]
Currently there's no timeline for stabilization of impl trait. What do you think about moving the current validators behind a `nightly` feature gate, and returning boxed closures when that feature is not enabled?

**Comment by ChrisBuchholz** [comment]
I have actually thought about this myself. I don't think it would take much time. I can surely get it done tomorrow or something if people would like it, which it sounds like you would, so yeah, I'll get it done for tomorrow, if something doesn't go wrong.

**Comment by ChrisBuchholz** [comment]
Alright, @sgrif, I choose to just do it now. I just released version 0.2.0 which doesn't require unstable rust. Next will be to begin adding cool unstable rust features via feature gates.

Shall we close this issue?

**Comment by ChrisBuchholz** [comment]
Alright, @sgrif, I choose to just do it now. I just released version ~0.2.0~ 0.2.1 which doesn't require unstable rust. Next will be to begin adding cool unstable rust features via feature gates.
Shall we close this issue?

**Comment by ChrisBuchholz** [comment]
I'm closing it.
